version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    depends_on:
      - redis
    networks:
      - app-network
  app:
    build: .
    command: bash -c "cd src && poetry run alembic upgrade head && poetry run python bot.py"
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  redis:
    image: redis:7.2.5
    container_name: redis
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis_data:/data
networks:
  app-network:
    driver: bridge
