version: '3.8'

services:
  #  src:
  #    container_name: src
  #    build: ./
  #    restart: on-failure
  #    command:
  #      - python src/presentation/src.py
  #    env_file:
  #      - .env
  #      -
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"