"""Create table users

Revision ID: 1f162e4c8fce
Revises: 
Create Date: 2024-07-11 12:08:27.268346+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f162e4c8fce"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_tg_id", sa.Integer(), nullable=False),
        sa.Column("hashed_tg_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("user_tg_id", name=op.f("pk_users")),
        sa.UniqueConstraint("id", name=op.f("uq_users_id")),
    )
    op.create_index(
        op.f("ix_users_hashed_tg_id"), "users", ["hashed_tg_id"], unique=True
    )
    op.create_index(
        op.f("ix_users_user_tg_id"), "users", ["user_tg_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_user_tg_id"), table_name="users")
    op.drop_index(op.f("ix_users_hashed_tg_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
